# Generated by Django 5.2 on 2025-09-02 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('login', 'Login'), ('logout', 'Logout')], max_length=20, verbose_name='Ação')),
                ('object_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Descrição do Objeto')),
                ('changes', models.JSONField(blank=True, help_text='JSON com as mudanças realizadas', null=True, verbose_name='Alterações')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividades',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='auditoria_a_created_c7e221_idx'), models.Index(fields=['actor', '-created_at'], name='auditoria_a_actor_i_ec1caf_idx'), models.Index(fields=['action', '-created_at'], name='auditoria_a_action_c4e64a_idx'), models.Index(fields=['content_type', '-created_at'], name='auditoria_a_content_70fa2a_idx')],
            },
        ),
    ]
