runtime: python312

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: "Athena.settings"

handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1