runtime: python312

env_variables:
  DJANGO_SETTINGS_MODULE: "Athena.Athena.settings"
  DEBUG: "False"

automatic_scaling:
  max_instances: 10
  min_instances: 0
  target_cpu_utilization: 0.65

entrypoint: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 Athena.Athena.wsgi:application