runtime: python312

env_variables:
  DJANGO_SETTINGS_MODULE: "Athena.Athena.settings"
  DEBUG: "False"
  SECRET_KEY: "django-insecure-)&($w&%4f*50780q86o_55c-9e_3ij7#+_6s7)0rsnv!ur%ekw"

automatic_scaling:
  max_instances: 10
  min_instances: 0
  target_cpu_utilization: 0.65

entrypoint: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 Athena.Athena.wsgi:application

handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /.*
  script: auto
  secure: always