runtime: python312

env_variables:
  DJANGO_SETTINGS_MODULE: "Athena.Athena.settings"

entrypoint: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 Athena.Athena.wsgi:application

# Arquivos a serem ignorados
skip_files:
- .git
- .gitignore
- README.md
- venv/
- __pycache__/