# Generated by Django 5.2 on 2025-08-07 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Estado')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('data_controller_name', models.CharField(max_length=150, verbose_name='Nome do Encarregado de Dados')),
                ('data_controller_email', models.EmailField(max_length=254, verbose_name='E-mail do Encarregado')),
                ('consent_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Consentimento')),
                ('data_processing_purpose', models.TextField(verbose_name='Finalidade do Tratamento')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.city', verbose_name='Cidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['corporate_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('consent_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Consentimento')),
                ('data_processing_purpose', models.TextField(verbose_name='Finalidade do Tratamento')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.city', verbose_name='Cidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.state', verbose_name='Estado'),
        ),
    ]

# Deploy: 2025-11-06 00:04:16
