# Generated by Django 5.2 on 2025-05-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PessoaJuridica',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='PessoaFisica',
            new_name='Person',
        ),
    ]
