# Generated by Django 5.2 on 2025-07-24 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_pessoajuridica_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['corporate_name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name'], 'verbose_name': 'Pessoa Física', 'verbose_name_plural': 'Pessoas Físicas'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='consent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Consentimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='corporate_name',
            field=models.CharField(default='', max_length=200, verbose_name='Razão Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='data_controller_email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail do Encarregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='data_controller_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nome do Encarregado de Dados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='data_processing_purpose',
            field=models.TextField(default='', verbose_name='Finalidade do Tratamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='company',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Controlador de Dados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='consent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Consentimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='data_processing_purpose',
            field=models.TextField(default='', verbose_name='Finalidade do Tratamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Controlador de Dados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Cidade'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.state', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail Corporativo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Estado'),
        ),
    ]
