# Generated by Django 5.2 on 2025-08-28 16:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_city_options_alter_company_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['corporate_name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='consent_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='data_controller_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='data_controller_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='consent_date',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Cidade'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='pages.state', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: 12.345.678/0001-90', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='corporate_name',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='data_processing_purpose',
            field=models.TextField(help_text='Descreva a finalidade do tratamento dos dados da empresa conforme LGPD', verbose_name='Finalidade do Tratamento de Dados'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_processing_purpose',
            field=models.TextField(help_text='Descreva a finalidade do tratamento dos dados pessoais conforme LGPD', verbose_name='Finalidade do Tratamento de Dados'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Contrato')),
                ('description', models.TextField(verbose_name='Descrição do Contrato')),
                ('contract_type', models.CharField(choices=[('servico', 'Prestação de Serviços'), ('trabalho', 'Contrato de Trabalho'), ('fornecimento', 'Fornecimento'), ('consultoria', 'Consultoria'), ('manutencao', 'Manutenção'), ('licenca', 'Licença de Software'), ('outro', 'Outro')], default='servico', max_length=20, verbose_name='Tipo de Contrato')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, help_text='Deixe em branco para contratos por prazo indeterminado', null=True, verbose_name='Data de Fim')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total do contrato em reais', max_digits=12, null=True, verbose_name='Valor do Contrato')),
                ('data_processing_purpose', models.TextField(help_text='Descreva como os dados serão tratados neste contrato (LGPD)', verbose_name='Finalidade do Tratamento de Dados no Contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='pages.company', verbose_name='Empresa')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='pages.person', verbose_name='Pessoa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
    ]
