# Generated by Django 5.2 on 2025-08-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_city_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o contrato está ativo no sistema', verbose_name='Contrato Ativo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('TRABALHO', 'Contrato de Trabalho'), ('SERVICO', 'Prestação de Serviços'), ('FORNECIMENTO', 'Fornecimento'), ('PARCERIA', 'Parceria'), ('OUTRO', 'Outro')], default='TRABALHO', max_length=50, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do contrato', verbose_name='Descrição'),
        ),
    ]

# Deploy: 2025-11-06 00:04:16
