# Generated by Django 5.2 on 2025-09-19 10:38

from django.db import migrations, connection


def remove_duplicate_index(apps, schema_editor):
    """Remove índice duplicado se existir"""
    with connection.cursor() as cursor:
        try:
            # Verificar se o índice existe
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'pages_company_usuario_id_f5dbd8d2'
            """)
            if cursor.fetchone():
                # Remover o índice duplicado
                cursor.execute("DROP INDEX pages_company_usuario_id_f5dbd8d2")
                print("✅ Índice duplicado removido com sucesso")
        except Exception as e:
            print(f"⚠️ Erro ao remover índice: {e}")


def reverse_remove_duplicate_index(apps, schema_editor):
    """Operação reversa - não faz nada"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0004_alter_city_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_index,
            reverse_remove_duplicate_index
        ),
    ]

# Criar nova migration para resolver o conflito:
# python manage.py makemigrations pages --empty --name fix_duplicate_index

# Deploy: 2025-11-06 00:04:16
