# Generated by Django 5.2 on 2025-10-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contract_is_active_alter_contract_contract_type_and_more'),
        ('pages', '0006_fix_duplicate_index'),
    ]

    operations = [
    ]

# Deploy: 2025-11-06 00:04:16
