# Generated by Django 5.2 on 2025-10-16 01:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def check_column_exists(apps, schema_editor):
    """Verifica se as colunas já existem antes de adicionar"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Verificar se consent_date existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='pages_company' 
            AND column_name='consent_date';
        """)
        return cursor.fetchone() is not None


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_merge_20251001_1946'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ✅ CRIAR MODELO ContractMovement PRIMEIRO
        migrations.CreateModel(
            name='ContractMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('activated', 'Ativado'), ('deactivated', 'Desativado'), ('deleted', 'Excluído')], max_length=30, verbose_name='Tipo de Movimento')),
                ('description', models.TextField(blank=True, default='', help_text='Detalhes sobre a movimentação', verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, help_text='Informações adicionais sobre a movimentação', null=True, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação de Contrato',
                'verbose_name_plural': 'Movimentações de Contratos',
                'ordering': ['-created_at'],
            },
        ),
        
        # ✅ REMOVER CAMPOS ANTIGOS
        migrations.RemoveField(
            model_name='company',
            name='data_processing_purpose',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        
        # ✅ ADICIONAR CAMPOS NOVOS (APENAS SE NÃO EXISTIREM)
        # Comentar temporariamente estas linhas:
        # migrations.AddField(
        #     model_name='company',
        #     name='consent_date',
        #     field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data em que o consentimento LGPD foi registrado', verbose_name='Data do Consentimento'),
        # ),
        
        migrations.AddField(
            model_name='company',
            name='consent_text',
            field=models.TextField(blank=True, default='', help_text='Termo de consentimento para tratamento de dados', verbose_name='Texto do Consentimento LGPD'),
        ),
        migrations.AddField(
            model_name='company',
            name='data_controller_email',
            field=models.EmailField(blank=True, default='', help_text='E-mail de contato do DPO', max_length=254, verbose_name='E-mail do Encarregado'),
        ),
        migrations.AddField(
            model_name='company',
            name='data_controller_name',
            field=models.CharField(blank=True, default='', help_text='Nome do DPO (Data Protection Officer)', max_length=150, verbose_name='Nome do Encarregado de Dados'),
        ),
        migrations.AddField(
            model_name='company',
            name='total_contracts',
            field=models.IntegerField(default=0, help_text='Número total de contratos ativos vinculados a esta empresa', verbose_name='Total de Contratos'),
        ),
        
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.state', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('TRABALHO', 'Contrato de Trabalho'), ('SERVICO', 'Prestação de Serviços'), ('FORNECIMENTO', 'Fornecimento'), ('PARCERIA', 'Parceria'), ('OUTRO', 'Outro')], default='SERVICO', max_length=20, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_processing_purpose',
            field=models.TextField(blank=True, default='', help_text='Descreva como os dados serão tratados neste contrato (LGPD)', verbose_name='Finalidade do Tratamento de Dados no Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descrição detalhada do contrato', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_processing_purpose',
            field=models.TextField(blank=True, default='', help_text='Descreva a finalidade do tratamento dos dados pessoais conforme LGPD', verbose_name='Finalidade do Tratamento de Dados'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'is_active'], name='pages_contr_company_77b82e_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['person', 'is_active'], name='pages_contr_person__0329cb_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-created_at'], name='pages_contr_created_01bd0f_idx'),
        ),
        migrations.AddField(
            model_name='contractmovement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pages.contract', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='contractmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_movements', to=settings.AUTH_USER_MODEL, verbose_name='Executado por'),
        ),
        migrations.AddIndex(
            model_name='contractmovement',
            index=models.Index(fields=['contract', '-created_at'], name='pages_contr_contrac_d5ba5a_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='pages_contr_movemen_73aa14_idx'),
        ),
    ]

# Deploy: 2025-11-06 00:04:16
