# Generated by Django 5.2 on 2025-11-06 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_add_company_lgpd_fields_and_contract_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='consent_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data em que o consentimento LGPD foi registrado', verbose_name='Data do Consentimento'),
        ),
    ]
